# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env:
        - MODULE=scipy
    - python: 2.7
      env:
        - MODULE=pandas
    - python: 2.7
      env:
        - MODULE=sklearn
    - python: 2.7
      env:
        - MODULE=astropy
    - python: 2.7
      env:
        - MODULE=matplotlib
    - python: 2.7
      env:
        - MODULE=statsmodels
    - python: 2.7
      env:
        - MODULE=skimage
    - python: 2.7
      env:
        - MODULE=numba
        - LLVM_CONFIG=llvm-config-3.6
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
    - llvm-3.6-dev
    - libedit-dev
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.f90cache
    - $HOME/.cache/pip
install:
  - |
    set -e
    tar xzf ci/f90cache-0.96.tar.gz
    pushd f90cache-0.96
    patch -p1 < ../ci/f90cache.patch
    ./configure --prefix=$HOME/f90cache
    make install
    ln -s $HOME/f90cache/bin/f90cache $HOME/f90cache/bin/gfortran
    popd
  - export PATH=$HOME/f90cache/bin:$PATH
  - pip install virtualenv
script:
  - python run.py -g $MODULE
notifications:
  email: false
