# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env:
        - MODULE=scipy
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libgmp-dev
    - libmpfr-dev
    - ccache
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
script:
  - python run.py -g $MODULE
notifications:
  email: false
